version: "3.8"

services:
  web:
    build: .
    image: mattdf93/rootgame:v1.0.7
    profiles: ["prod"]
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    env_file:
      - .env.prod
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    ports:
      - "8000:8000"

  cloudflared:
    image: cloudflare/cloudflared:latest
    profiles: ["prod"]
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_KEY}
    depends_on:
      - web

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
