# Generated by Django 5.0.6 on 2026-05-19 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_revealedcardentry_returned_to_hand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mob',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.token')),
            ],
            bases=('game.token',),
        ),
        migrations.CreateModel(
            name='Stronghold',
            fields=[
                ('building_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.building')),
                ('crafted_with', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('game.building', models.Model),
        ),
        migrations.CreateModel(
            name='Warlord',
            fields=[
                ('warrior_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.warrior')),
            ],
            bases=('game.warrior',),
        ),
        migrations.AlterField(
            model_name='gamelog',
            name='log_type',
            field=models.CharField(choices=[('TURN', 'Turn'), ('PHASE', 'Phase'), ('MOVE', 'Move'), ('BATTLE', 'Battle'), ('CRAFT', 'Craft'), ('DRAW', 'Draw'), ('DISCARD', 'Discard'), ('AMBUSH', 'Ambush'), ('DICE_ROLL', 'Dice Roll'), ('PIECE_REMOVAL', 'Piece Removal'), ('CATS_BIRDS_FOR_HIRE', 'Cats Birds for Hire'), ('CATS_MARCH', 'Cats March'), ('CATS_WOOD_PLACEMENT', 'Cats Wood Placement'), ('CATS_BUILD', 'Cats Build'), ('CATS_OVERWORK', 'Cats Overwork'), ('CATS_RECRUIT', 'Cats Recruit'), ('CATS_SETUP_PICK_CORNER', 'Cats Setup Pick Corner'), ('CATS_SETUP_PLACE_BUILDING', 'Cats Setup Place Building'), ('BIRDS_ADD_TO_DECREE', 'Birds Add To Decree'), ('BIRDS_EMERGENCY_ROOST', 'Birds Emergency Roost'), ('BIRDS_DECREE_ACTION', 'Birds Decree Action'), ('BIRDS_SCORE_ROOSTS', 'Birds Score Roosts'), ('BIRDS_TURMOIL', 'Birds Turmoil'), ('BIRDS_NEW_LEADER', 'Birds New Leader'), ('BIRDS_SETUP_PICK_CORNER', 'Birds Setup Pick Corner'), ('BIRDS_SETUP_CHOOSE_LEADER', 'Birds Setup Choose Leader'), ('WA_REVOLT', 'Woodland Revolt'), ('WA_SPREAD_SYMPATHY', 'Woodland Spread Sympathy'), ('WA_MOBILIZE', 'Woodland Mobilize'), ('WA_TRAIN', 'Woodland Train'), ('WA_ORGANIZE', 'Woodland Organize'), ('WA_MILITARY_OPERATION', 'Woodland Military Operation'), ('WA_OUTRAGE', 'Woodland Outrage'), ('WA_BASE_REMOVED', 'Woodland Base Removed'), ('WA_OFFICERS_LOST', 'Woodland Officers Lost'), ('WA_SUPPORTERS_LOST', 'Woodland Supporters Lost'), ('CROWS_PLOT', 'Crows Plot'), ('CROWS_FLIP', 'Crows Flip'), ('CROWS_RECRUIT', 'Crows Recruit'), ('CROWS_TRICK', 'Crows Trick'), ('CROWS_EXPOSURE', 'Crows Exposure'), ('CROWS_RAID', 'Crows Raid'), ('CROWS_SETUP_PLACE_WARRIOR', 'Crows Setup Place Warrior'), ('CROWS_EXTORTION_STOLE_CARD', 'Crows Extortion Stole Card'), ('MOLES_SETUP_PICK_CORNER', 'Moles Setup Pick Corner'), ('MOLES_BIRDSONG_PLACE_WARRIORS', 'Moles Birdsong Place Warriors'), ('MOLES_BUILD', 'Moles Build'), ('MOLES_RECRUIT', 'Moles Recruit'), ('MOLES_DIG', 'Moles Dig'), ('MOLES_SWAY_MINISTER', 'Moles Sway Minister'), ('MOLES_MINISTER_MARSHAL', 'Moles Minister Marshal'), ('MOLES_MINISTER_CAPTAIN', 'Moles Minister Captain'), ('MOLES_MINISTER_FOREMOLE', 'Moles Minister Foremole'), ('MOLES_MINISTER_BANKER', 'Moles Minister Banker'), ('MOLES_MINISTER_DUCHESS', 'Moles Minister Duchess of Mud'), ('MOLES_MINISTER_BARON', 'Moles Minister Baron of Dirt'), ('MOLES_MINISTER_EARL', 'Moles Minister Earl of Stone'), ('MOLES_MINISTER_BRIGADIER', 'Moles Minister Brigadier'), ('MOLES_MINISTER_MAYOR', 'Moles Minister Mayor'), ('MOLES_EVENING_PROCESS_REVEALED', 'Moles Evening Process Revealed Cards'), ('MOLES_PRICE_OF_FAILURE', 'Moles Price of Failure'), ('CATS_FIELD_HOSPITALS', 'Field Hospitals'), ('CRAFTED_CARD_ACTION', 'Crafted Card Action')], max_length=50),
        ),
        migrations.CreateModel(
            name='CommandItemEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.item')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_items', to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentMood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_type', models.CharField(choices=[('bitter', 'Bitter'), ('grandiose', 'Grandiose'), ('jubilant', 'Jubilant'), ('lavish', 'Lavish'), ('relentless', 'Relentless'), ('rowdy', 'Rowdy'), ('stubborn', 'Stubborn'), ('wrathful', 'Wrathful')], max_length=10)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mood', to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='ProwessItemEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.item')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prowess_items', to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='RatsSimpleSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('1', 'Picking Corner'), ('2', 'Pending Confirmation'), ('3', 'Completed')], default='1', max_length=1)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='RatsTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.PositiveSmallIntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='RatsEvening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('0', 'Not Started'), ('1', 'Incite'), ('2', 'Oppress'), ('3', 'Draw'), ('4', 'Discard'), ('z', 'Before End'), ('5', 'Completed')], default='0', max_length=1)),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evening', to='game.ratsturn')),
            ],
        ),
        migrations.CreateModel(
            name='RatsDaylight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('0', 'Not Started'), ('1', 'Craft'), ('2', 'Command'), ('3', 'Advance'), ('z', 'Before End'), ('4', 'Completed')], default='0', max_length=1)),
                ('commands_used', models.IntegerField(default=0)),
                ('prowess_used', models.IntegerField(default=0)),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daylight', to='game.ratsturn')),
            ],
        ),
        migrations.CreateModel(
            name='RatsBirdsong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('0', 'Not Started'), ('1', 'Raze'), ('2', 'Spread Mob'), ('3', 'Recruit'), ('4', 'Anoint'), ('5', 'Choose Mood'), ('z', 'Before End'), ('6', 'Completed')], default='0', max_length=1)),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birdsong', to='game.ratsturn')),
            ],
        ),
        migrations.AddConstraint(
            model_name='ratssimplesetup',
            constraint=models.UniqueConstraint(fields=('player',), name='unique_rats_setup_per_player'),
        ),
    ]
