# Generated by Django 5.0.6 on 2026-05-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_mob_stronghold_warlord_alter_gamelog_log_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='attacker',
            field=models.CharField(choices=[('ca', 'Cats'), ('bi', 'Birds'), ('wa', 'Woodland Alliance'), ('cr', 'Crows'), ('mo', 'Moles'), ('ra', 'Rats')], max_length=2),
        ),
        migrations.AlterField(
            model_name='battle',
            name='defender',
            field=models.CharField(choices=[('ca', 'Cats'), ('bi', 'Birds'), ('wa', 'Woodland Alliance'), ('cr', 'Crows'), ('mo', 'Moles'), ('ra', 'Rats')], max_length=2),
        ),
        migrations.AlterField(
            model_name='factionchoiceentry',
            name='faction',
            field=models.CharField(choices=[('ca', 'Cats'), ('bi', 'Birds'), ('wa', 'Woodland Alliance'), ('cr', 'Crows'), ('mo', 'Moles'), ('ra', 'Rats')], max_length=2),
        ),
        migrations.AlterField(
            model_name='gamesimplesetup',
            name='status',
            field=models.CharField(choices=[('INIT', 'Initial Setup'), ('CAT', 'Cats Setup'), ('BIRD', 'Birds Setup'), ('WA', 'Woodland Alliance Setup'), ('VB', 'Vagabond Setup'), ('CROW', 'Crows Setup'), ('MOL', 'Moles Setup'), ('RAT', 'Rats Setup'), ('COMP', 'Completed')], default='INIT', max_length=4),
        ),
        migrations.AlterField(
            model_name='player',
            name='faction',
            field=models.CharField(blank=True, choices=[('ca', 'Cats'), ('bi', 'Birds'), ('wa', 'Woodland Alliance'), ('cr', 'Crows'), ('mo', 'Moles'), ('ra', 'Rats')], max_length=2, null=True),
        ),
    ]
