# Generated by Django 5.0.6 on 2026-05-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_alter_battle_attacker_alter_battle_defender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratsbirdsong',
            name='mob_die_suit',
            field=models.CharField(blank=True, choices=[('r', 'Fox'), ('y', 'Rabbit'), ('o', 'Mouse'), ('b', 'Bird')], default=None, max_length=1, null=True),
        ),
    ]
