# Generated by Django 5.0.6 on 2026-05-19 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0030_ratsbirdsong_mob_die_suit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('battle', 'Battle'), ('field_hospital', 'Field Hospital'), ('turmoil', 'Turmoil'), ('outrage', 'Outrage'), ('informants', 'Informants'), ('saboteurs', 'Saboteurs'), ('eyrie_emigre', 'Eyrie Emigre'), ('charm_offensive', 'Charm Offensive'), ('partisans', 'Partisans'), ('swap_meet', 'Swap Meet'), ('crow_recruit', 'Crow Recruit'), ('place_raid_warriors', 'Place Raid Warriors'), ('price_of_failure', 'Price Of Failure'), ('hoard_too_full', 'Hoard Too Full')], max_length=50),
        ),
        migrations.CreateModel(
            name='HoardTooFullEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(choices=[('command', 'Command'), ('prowess', 'Prowess')], max_length=10)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hoard_too_full', to='game.event')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoard_too_full_events', to='game.player')),
            ],
        ),
    ]
