# Generated by Django 5.0.6 on 2026-05-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0031_hoard_too_full_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='stronghold',
            name='recruit_used',
            field=models.BooleanField(default=False),
        ),
    ]
