# Generated by Django 5.0.6 on 2026-05-19 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0033_rats_advance_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('battle', 'Battle'), ('field_hospital', 'Field Hospital'), ('turmoil', 'Turmoil'), ('outrage', 'Outrage'), ('informants', 'Informants'), ('saboteurs', 'Saboteurs'), ('eyrie_emigre', 'Eyrie Emigre'), ('charm_offensive', 'Charm Offensive'), ('partisans', 'Partisans'), ('swap_meet', 'Swap Meet'), ('crow_recruit', 'Crow Recruit'), ('place_raid_warriors', 'Place Raid Warriors'), ('price_of_failure', 'Price Of Failure'), ('hoard_too_full', 'Hoard Too Full'), ('looting', 'Looting')], max_length=50),
        ),
        migrations.CreateModel(
            name='LootingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='looting', to='game.event')),
                ('looted_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='being_looted_events', to='game.player')),
                ('looting_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='looting_events', to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='RatsPlayerState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('looting_declared', models.BooleanField(default=False)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rats_state', to='game.player')),
            ],
        ),
    ]
