# Generated by Django 5.0.6 on 2026-05-19 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0034_rats_looting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='step',
            field=models.CharField(choices=[('1', 'Defender Ambush'), ('2', 'Attacker Ambush'), ('3', 'Attacker Chooses Ambush Hits'), ('8', 'Rats Bitter Check'), ('4', 'Roll Dice'), ('5', 'Defender Chooses Hits'), ('6', 'Attacker Chooses Hits'), ('7', 'Completed')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('battle', 'Battle'), ('field_hospital', 'Field Hospital'), ('turmoil', 'Turmoil'), ('outrage', 'Outrage'), ('informants', 'Informants'), ('saboteurs', 'Saboteurs'), ('eyrie_emigre', 'Eyrie Emigre'), ('charm_offensive', 'Charm Offensive'), ('partisans', 'Partisans'), ('swap_meet', 'Swap Meet'), ('crow_recruit', 'Crow Recruit'), ('place_raid_warriors', 'Place Raid Warriors'), ('price_of_failure', 'Price Of Failure'), ('hoard_too_full', 'Hoard Too Full'), ('looting', 'Looting'), ('bitter_resolve', 'Bitter Resolve')], max_length=50),
        ),
        migrations.CreateModel(
            name='ResolveBitterEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitter_events', to='game.battle')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bitter', to='game.event')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitter_events', to='game.player')),
            ],
        ),
    ]
