# Generated by Django 5.0.6 on 2026-05-20 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0035_rats_bitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('battle', 'Battle'), ('field_hospital', 'Field Hospital'), ('turmoil', 'Turmoil'), ('outrage', 'Outrage'), ('informants', 'Informants'), ('saboteurs', 'Saboteurs'), ('eyrie_emigre', 'Eyrie Emigre'), ('charm_offensive', 'Charm Offensive'), ('partisans', 'Partisans'), ('swap_meet', 'Swap Meet'), ('crow_recruit', 'Crow Recruit'), ('place_raid_warriors', 'Place Raid Warriors'), ('price_of_failure', 'Price Of Failure'), ('hoard_too_full', 'Hoard Too Full'), ('looting', 'Looting'), ('bitter_resolve', 'Bitter Resolve'), ('jubilant_mob_spread', 'Jubilant Mob Spread')], max_length=50),
        ),
        migrations.CreateModel(
            name='JubilantMobSpreadEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolls_remaining', models.PositiveSmallIntegerField(default=4)),
                ('current_roll', models.CharField(blank=True, choices=[('r', 'Fox'), ('y', 'Rabbit'), ('o', 'Mouse'), ('b', 'Bird')], max_length=10, null=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jubilant_mob_spread', to='game.event')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jubilant_mob_spread_events', to='game.player')),
            ],
        ),
    ]
