# Generated by Django 5.0.6 on 2026-05-21 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0036_alter_event_type_jubilantmobspreadevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratsbirdsong',
            name='lavish_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('battle', 'Battle'), ('field_hospital', 'Field Hospital'), ('turmoil', 'Turmoil'), ('outrage', 'Outrage'), ('informants', 'Informants'), ('saboteurs', 'Saboteurs'), ('eyrie_emigre', 'Eyrie Emigre'), ('charm_offensive', 'Charm Offensive'), ('partisans', 'Partisans'), ('swap_meet', 'Swap Meet'), ('crow_recruit', 'Crow Recruit'), ('place_raid_warriors', 'Place Raid Warriors'), ('price_of_failure', 'Price Of Failure'), ('hoard_too_full', 'Hoard Too Full'), ('looting', 'Looting'), ('bitter_resolve', 'Bitter Resolve'), ('jubilant_mob_spread', 'Jubilant Mob Spread'), ('lavish', 'Lavish')], max_length=50),
        ),
        migrations.CreateModel(
            name='LavishEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lavish', to='game.event')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lavish_events', to='game.player')),
            ],
        ),
    ]
